FROM f9teams/zmc-build

WORKDIR /tmp
# This is my hack to trick Zimbra into picking up the eventual hostname, instead
# of the current Docker assigned hostname. Zimbra has some goofy rules, example;
# a FQDN must have 2 or more '.'s
COPY ./hostname ./hack/hostname
RUN chmod +x ./hack/hostname

COPY ./mta/install-mta ./install-mta
RUN tar xfz release-zimbra-8.tgz
RUN export PATH=/tmp/hack:$PATH && \
    echo "`hostname -i` `hostname --fqdn`" >> /etc/hosts && \
    cd /tmp/zcs-* && \
    ./install.sh -s < /tmp/install-mta

COPY ./zmc-config ./zmc-config
COPY ./mta/mta-config ./mta-config
RUN cat ./zmc-config ./mta-config | sed '/^\s*$/d' >> ./config

WORKDIR /opt/zimbra
COPY ./mta/mta-entrypoint ./mta-entrypoint
RUN chmod +x ./mta-entrypoint && \
    mv /tmp/healthcheck.py ./healthcheck.py

ENTRYPOINT ./mta-entrypoint
EXPOSE 22 25 465 587 110 143 993 995 80 443 8080 8443 7071
