FROM f9teams/zmc-build

WORKDIR /tmp
# This is my hack to trick Zimbra into picking up the eventual hostname, instead
# of the current Docker assigned hostname. Zimbra has some goofy rules, example;
# a FQDN must have 2 or more '.'s
COPY ./hostname ./hack/hostname
RUN chmod +x ./hack/hostname

COPY ./mysql/install ./install
RUN export PATH=/tmp/hack:$PATH && \
    echo "`hostname -i` `hostname --fqdn`" >> /etc/hosts && \
    cd /tmp/BUILDS/*/*/*/zm-build/zcs-* && \
    ./install.sh -s < /tmp/install

COPY ./zmc-config ./zmc-config
COPY ./mysql/config ./mysql-config
RUN cat ./zmc-config ./mysql-config | sed '/^\s*$/d' >> ./config

WORKDIR /opt/zimbra
COPY ./mysql/entrypoint ./entrypoint
COPY ./mysql/healthcheck.py ./healthcheck.py
RUN chmod +x ./healthcheck.py

RUN chmod +x ./entrypoint

ENTRYPOINT ./entrypoint
EXPOSE 22 5000 7306
