FROM zimbra/zmc-base

WORKDIR /tmp

COPY ./mailbox/install-mailbox ./install-mailbox
RUN cd /zimbra/release && \
    ./install.sh -s < /tmp/install-mailbox

COPY ./zmc-config ./zmc-config
COPY ./mailbox/mailbox-config ./mailbox-config
RUN cat ./zmc-config ./mailbox-config | sed '/^\s*$/d' >> ./config

WORKDIR /opt/zimbra
COPY ./mailbox/mailbox-entrypoint ./mailbox-entrypoint
RUN chmod +x ./mailbox-entrypoint && \
    mv /zimbra/healthcheck.py ./healthcheck.py

ENTRYPOINT ./mailbox-entrypoint
EXPOSE 22 25 465 587 110 143 993 995 80 443 8080 8443 7071
