FROM zimbra/zmc-base

WORKDIR /tmp
# This is my hack to trick Zimbra into picking up the eventual hostname, instead
# of the current Docker assigned hostname. Zimbra has some goofy rules, example;
# a FQDN must have 2 or more '.'s
COPY ./hostname ./hack/hostname
RUN chmod +x ./hack/hostname

COPY ./mailbox/install-mailbox ./install-mailbox
RUN export PATH=/tmp/hack:$PATH && \
    echo "`hostname -i` `hostname --fqdn`" >> /etc/hosts && \
    cd /zimbra/release && \
    ./install.sh -s < /tmp/install-mailbox \
    chown zimbra:zimbra /opt/zimbra

COPY ./zmc-config ./zmc-config
COPY ./mailbox/mailbox-config ./mailbox-config
RUN cat ./zmc-config ./mailbox-config | sed '/^\s*$/d' >> ./config

WORKDIR /opt/zimbra
COPY ./mailbox/mailbox-entrypoint ./mailbox-entrypoint
RUN chmod +x ./mailbox-entrypoint && \
    mv /zimbra/healthcheck.py ./healthcheck.py

ENTRYPOINT ./mailbox-entrypoint
EXPOSE 22 25 465 587 110 143 993 995 80 443 8080 8443 7071
