FROM zimbra/zmc-base

WORKDIR /tmp

COPY ./mysql/install ./install
RUN cd /zimbra/release && \
    ./install.sh -s < /tmp/install

COPY ./zmc-config ./zmc-config
COPY ./mysql/config ./mysql-config
RUN cat ./zmc-config ./mysql-config | sed '/^\s*$/d' >> ./config

WORKDIR /opt/zimbra
COPY ./mysql/entrypoint ./entrypoint
COPY ./mysql/healthcheck.py ./healthcheck.py
RUN chmod +x ./healthcheck.py

RUN chmod +x ./entrypoint

ENTRYPOINT ./entrypoint
EXPOSE 22 5000 7306
