FROM zimbra/zmc-base

WORKDIR /tmp

COPY ./proxy/install-proxy ./install-proxy
RUN cd /zimbra/release && \
    ./install.sh -s < /tmp/install-proxy

COPY ./zmc-config ./zmc-config
COPY ./proxy/proxy-config ./proxy-config
RUN cat ./zmc-config ./proxy-config | sed '/^\s*$/d' >> ./config

WORKDIR /opt/zimbra
COPY ./proxy/proxy-entrypoint ./proxy-entrypoint
RUN chmod +x ./proxy-entrypoint && \
    mv /zimbra/healthcheck.py ./healthcheck.py

ENTRYPOINT ./proxy-entrypoint
EXPOSE 22 25 465 587 110 143 993 995 80 443 8080 8443 7071
