FROM zimbra/zmc-base

WORKDIR /tmp

COPY ./mta/install-mta ./install-mta
RUN cd /zimbra/release && \
    ./install.sh -s < /tmp/install-mta

COPY ./zmc-config ./zmc-config
COPY ./mta/mta-config ./mta-config
RUN cat ./zmc-config ./mta-config | sed '/^\s*$/d' >> ./config

WORKDIR /opt/zimbra
COPY ./mta/mta-entrypoint ./mta-entrypoint
RUN chmod +x ./mta-entrypoint && \
    mv /zimbra/healthcheck.py ./healthcheck.py

ENTRYPOINT ./mta-entrypoint
EXPOSE 22 25 465 587 110 143 993 995 80 443 8080 8443 7071
