FROM zimbra/zmc-base

WORKDIR /tmp

COPY ./ldap/install-ldap ./install-ldap
RUN cd /zimbra/release && \
    ./install.sh -s < /tmp/install-ldap

COPY ./zmc-config ./zmc-config
COPY ./ldap/ldap-config ./ldap-config
RUN cat ./zmc-config ./ldap-config | sed '/^\s*$/d' >> ./config

WORKDIR /opt/zimbra
COPY ./ldap/ldap-entrypoint ./ldap-entrypoint
RUN chmod +x ./ldap-entrypoint && \
    mv /zimbra/healthcheck.py ./healthcheck.py

ENTRYPOINT ./ldap-entrypoint
EXPOSE 22 25 465 587 110 143 993 995 80 443 8080 8443 7071
