#! /bin/bash

echo "Waiting for LDAP"
status=$(curl --silent --output /dev/null --write-out "%{http_code}" http://ldap:5000/)
while [ $status -ne 200 ]; do
  echo "LDAP unavailable"
  sleep 20
  status=$(curl --silent --output /dev/null --write-out "%{http_code}" http://ldap:5000/)
done
echo "LDAP available"

if [ ! -f /zimbra/configured ]; then
    echo "Configuring MTA"
    /opt/zimbra/libexec/zmsetup.pl -c /tmp/config
    status=$?
    if [ $status -ne 0 ]; then
      echo "Failed to configure MTA: $status"
      exit $status
    fi

    # Disable LDAP TLS Use
    # TODO this should be controlled via ldap_starttls_supported="0"
    # but it doesn't seem to be picked up when fed via config
    pushd /opt/zimbra
    sudo -u zimbra /opt/zimbra/bin/zmlocalconfig -e ldap_starttls_required=false
    sudo -u zimbra /opt/zimbra/bin/zmlocalconfig -e ldap_starttls_supported=0
    popd

    touch /zimbra/configured
else
    # Bad shutdowns will leave containers in an unstable state for the next start.
    # Ensure no latent PID files are hanging around that trick startup into
    # thinking things are running.

    echo "Wiping old PID files..."
    zm_log_dir=$(/opt/zimbra/bin/zmlocalconfig -x -m nokey zimbra_log_directory)
    rm -f $zm_log_dir/*.pid
fi

sudo -u zimbra /opt/zimbra/bin/zmcontrol start

# TODO: not sure if this is necessary
su -c /opt/zimbra/bin/zmupdateauthkeys zimbra

cleanup() {
    code=$?
    sudo -u zimbra /opt/zimbra/bin/zmcontrol stop
    exit $code
}

trap "cleanup" INT TERM EXIT

# start simple healthcheck so other nodes in the cluster can coordinate startup
echo "MTA started"
/zimbra/healthcheck.py &
wait
