#! /bin/bash

echo "Waiting for LDAP"
status=$(curl --silent --output /dev/null --write-out "%{http_code}" http://ldap:5000/)
while [ $status -ne 200 ]; do
  echo "LDAP unavailable"
  sleep 20
  status=$(curl --silent --output /dev/null --write-out "%{http_code}" http://ldap:5000/)
done
echo "LDAP available"

/opt/zimbra/libexec/zmsetup.pl -c /tmp/config
status=$?
if [ $status -ne 0 ]; then
  echo "Failed to start MTA: $status"
  exit $status
fi

# TODO: not sure if this is necessary
su -c /opt/zimbra/bin/zmupdateauthkeys zimbra

# start simple healthcheck so other nodes in the cluster can coordinate startup
echo "MTA started"
/zimbra/healthcheck.py
