#! /bin/bash

echo "Waiting for LDAP"
status=$(curl --silent --output /dev/null --write-out "%{http_code}" http://zmc-ldap.f9teams.engineering:5000/)
while [ $status -ne 200 ]; do
  echo "LDAP unavailable"
  sleep 20
  status=$(curl --silent --output /dev/null --write-out "%{http_code}" http://zmc-ldap.f9teams.engineering:5000/)
done
echo "LDAP available"

/opt/zimbra/libexec/zmsetup.pl -c /tmp/config
status=$?
if [ $status -ne 0 ]; then
  echo "Failed to start MTA: $status"
  exit $status
fi

# TODO: not sure if this is necessary
su -c /opt/zimbra/bin/zmupdateauthkeys zimbra

# start simple healthcheck so other nodes in the cluster can coordinate startup
echo "MTA started"
./healthcheck.py

white /bin/true; do
  su -c "/opt/zimbra/bin/zmcontrol status" zimbra |grep Stopped
  ZMC_STATUS=$?
  if [ $ZMC_STATUS -ne 0 ]; then
    echo "One of the processes has exited"
    echo "restarted processes"
    su -c "/opt/zimbra/bin/zmcontrol start" zimbra
    echo "MAILBOX restarted"
  fi
  sleep 60
done
