#! /bin/bash

echo "Waiting for MAILBOX"
status=$(curl --silent --output /dev/null --write-out "%{http_code}" http://mailbox:5000/)
while [ $status -ne 200 ]; do
  echo "MAILBOX unavailable"
  sleep 20
  status=$(curl --silent --output /dev/null --write-out "%{http_code}" http://mailbox:5000/)
done
echo "MAILBOX available"

if [ ! -f /zimbra/configured ]; then
    echo "Configuring PROXY"
    /opt/zimbra/libexec/zmsetup.pl -c /tmp/config
    status=$?
    if [ $status -ne 0 ]; then
      echo "Failed to configure PROXY: $status"
      exit $status
    fi

    touch /zimbra/configured
else
    # Bad shutdowns will leave containers in an unstable state for the next start.
    # Ensure no latent PID files are hanging around that trick startup into
    # thinking things are running.

    echo "Wiping old PID files..."
    zm_log_dir=$(/opt/zimbra/bin/zmlocalconfig -x -m nokey zimbra_log_directory)
    rm -f $zm_log_dir/*.pid
fi

sudo -u zimbra /opt/zimbra/bin/zmcontrol start

# TODO: not sure if this is necessary
su -c /opt/zimbra/bin/zmupdateauthkeys zimbra

cleanup() {
    code=$?
    sudo -u zimbra /opt/zimbra/bin/zmcontrol stop
    exit $code
}

trap "cleanup" INT TERM EXIT

# start simple healthcheck so other nodes in the cluster can coordinate startup
echo "PROXY started"
/zimbra/healthcheck.py &
wait
