#! /bin/bash

echo "Waiting for LDAP"
status=$(curl --silent --output /dev/null --write-out "%{http_code}" http://zmc-ldap.f9teams.engineering:5000/)
while [ $status -ne 200 ]; do
  echo "LDAP unavailable"
  sleep 20
  status=$(curl --silent --output /dev/null --write-out "%{http_code}" http://zmc-ldap.f9teams.engineering:5000/)
done
echo "LDAP available"


/opt/zimbra/libexec/zmsetup.pl -c /tmp/config
status=$?
if [ $status -ne 0 ]; then
  echo "Failed to start MYSQL: $status"
  exit $status
fi

# remove the entry that only lets mysql listen on localhost. Yes this is gross.
sed -i -e '/bind-address/d' /opt/zimbra/conf/my.cnf
su -c '/opt/zimbra/bin/zmmypasswd f9teams' zimbra
su -c '/opt/zimbra/bin/zmmypasswd --root f9teams' zimbra

/opt/zimbra/bin/mysql -u root --password=f9teams -e 'grant all privileges on *.* to zimbra;'
su -c '/opt/zimbra/bin/zmcontrol stop' zimbra
su -c '/opt/zimbra/bin/zmprov deleteServer zmc-mysql.f9teams.engineering' zimbra
su -c '/opt/zimbra/bin/mysql.server start' zimbra
# TODO: not sure if this is necessary
su -c /opt/zimbra/bin/zmupdateauthkeys zimbra

# start simple healthcheck so other nodes in the cluster can coordinate startup
echo "MYSQL started"
./healthcheck.py
