#!/bin/bash
# Due to new schema added in develop, we have to force re-running
# migration version scripts that were previously applied.
# This should be executed as the zimbra user

echo "$0 - running database migration scripts"
echo "Resetting db.version prior to running migration scripts"
/opt/zimbra/bin/mysql <<EOF
update zimbra.config set value=108 where  name='db.version';
EOF
inc_common="/opt/zimbra/common/lib/perl5/x86_64-linux-gnu-thread-multi"
inc_scripts="/opt/zimbra/libexec/scripts"
mkdir -p /opt/zimbra/db/data/chat
chown zimbra:zimbra /opt/zimbra/db/data/chat
echo "Running migrate20180301-ZimbraChat.pl"
/usr/bin/perl -I${inc_common} -I${inc_scripts} /opt/zimbra/libexec/scripts/migrate20180301-ZimbraChat.pl
echo "Running migrate20170829-SearchHistory.pl"
/usr/bin/perl -I${inc_common} -I${inc_scripts} /opt/zimbra/libexec/scripts/migrate20170829-SearchHistory.pl
echo "Running migrate20180110-DistributedRedolog.pl"
/usr/bin/perl -I${inc_common} -I${inc_scripts} /opt/zimbra/libexec/scripts/migrate20180110-DistributedRedolog.pl
echo "DB migration complete"
