FROM anapsix/alpine-java:jdk7

ENV ANT_VERSION 1.10.1
ENV ANT_HOME /etc/ant-${ANT_VERSION}

# Installation

RUN cd /tmp \
    && wget http://www.us.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz \
    && mkdir ant-${ANT_VERSION} \
    && tar -zxvf apache-ant-${ANT_VERSION}-bin.tar.gz \
    && mv apache-ant-${ANT_VERSION} ${ANT_HOME} \
    && rm apache-ant-${ANT_VERSION}-bin.tar.gz \
    && rm -rf ant-${ANT_VERSION} \
    && rm -rf ${ANT_HOME}/manual \
    && unset ANT_VERSION
ENV PATH ${PATH}:${ANT_HOME}/bin

#############
# Ant Contrib
#############

# Preparation

ENV ANT_CONTRIB_VERSION 1.0b5

# Installation

RUN cd /tmp \
    && wget http://kent.dl.sourceforge.net/project/ant-contrib/ant-contrib/ant-contrib-${ANT_CONTRIB_VERSION}/ant-contrib-${ANT_CONTRIB_VERSION}-bin.tar.gz \
    && tar -zxvf ant-contrib-${ANT_CONTRIB_VERSION}-bin.tar.gz \
    && cp ant-contrib/lib/ant-contrib.jar ${ANT_HOME}/lib \
    && rm -rf ant-contrib \
    && rm ant-contrib-${ANT_CONTRIB_VERSION}-bin.tar.gz \
    && unset ANT_CONTRIB_VERSION

RUN apk update && \
  apk-install \
# install basics
  vim \
  wget \
  curl \
  gettext \
  slay \
  python \
  python-pip \
# install zimbra pre-requisites
#  apache-ant \
# ant-contrib \
  build-essential \
  git \
  maven \
  openjdk-8-jdk \
  ruby \
  net-tools \
  rsyslog \
  software-properties-common \
  npm

RUN npm install -g n && \
    n latest

RUN npm install -g junit-merge

RUN echo "resolvconf resolvconf/linkify-resolvconf boolean false" | debconf-set-selections
