#!/bin/bash
# This script uses the following environment variables to control how SOLR is started and configured
# SOLR_MODE cloud|standalone
# SOLR_MEMORY <solr-memory-allocation-spec>

[ -z "$SOLR_MODE" ] && echo "SOLR_MODE not defined" && exit 1
[ -z "$SOLR_MEMORY" ] && echo "SOLR_MEMORY not defined" && exit 1

echo "Starting SOLR in $SOLR_MODE mode with $SOLR_MEMORY RAM"

if [ "$SOLR_MODE" = "cloud" ]; then
	/opt/solr/bin/solr start -c -m $SOLR_MEMORY
	/opt/solr/bin/solr zk upconfig -n zimbra -d /opt/solr/server/solr/configsets/zimbra/ -z localhost:9983
	/opt/solr/bin/solr zk upconfig -n zimbra -d /opt/solr/server/solr/configsets/events/ -z localhost:9983
else
	/opt/solr/bin/solr start -m $SOLR_MEMORY
fi
echo "SOLR STARTUP COMPLETE"
sleep infinity
