#! /bin/bash

echo "Waiting for MTA"
status=$(curl --silent --output /dev/null --write-out "%{http_code}" http://mta:5000/)
while [ $status -ne 200 ]; do
  echo "MTA unavailable"
  sleep 20
  status=$(curl --silent --output /dev/null --write-out "%{http_code}" http://mta:5000/)
done
echo "MTA available"

if [ ! -f /zimbra/configured ]; then
    echo "Setting MAILBOX configuration..."

    /opt/zimbra/libexec/zmsetup.pl -c /tmp/config
    status=$?
    if [ $status -ne 0 ]; then
      echo "Failed to configure MAILBOX: $status"
      exit $status
    fi

    touch /zimbra/configured
fi

echo "Starting MAILBOX"
sudo -u zimbra /opt/zimbra/bin/zmcontrol start

# TODO: not sure if this is necessary
su -c /opt/zimbra/bin/zmupdateauthkeys zimbra

# start simple healthcheck so other nodes in the cluster can coordinate startup
echo "MAILBOX started"
/zimbra/healthcheck.py
