#! /bin/bash

echo "Waiting for MTA"
status=$(curl --silent --output /dev/null --write-out "%{http_code}" http://zmc-mta:5000/)
while [ $status -ne 200 ]; do
  echo "MTA unavailable"
  sleep 20
  status=$(curl --silent --output /dev/null --write-out "%{http_code}" http://zmc-mta:5000/)
done
echo "MTA available"

echo "Waiting for MYSQL"
status=$(curl --silent --output /dev/null --write-out "%{http_code}" http://zmc-mysql:5000/)
while [ $status -ne 200 ]; do
  echo "MYSQL unavailable"
  sleep 20
  status=$(curl --silent --output /dev/null --write-out "%{http_code}" http://zmc-mysql:5000/)
done
echo "MYSQL available"

# FIXME: THE CASE WHERE zmcontrol insists on checking for local mysqld
#  zmcontrol status
#  Host zmc-mailbox
#          imapd                   Running
#          mailbox                 Stopped
#                  mysql.server is not running.
#          service webapp          Stopped
#                  mysql.server is not running.
#          spell                   Running
#          stats                   Stopped
#          zimbra webapp           Stopped
#                  mysql.server is not running.
#          zimbraAdmin webapp      Stopped
#                  mysql.server is not running.
#          zimlet webapp           Stopped
#                  mysql.server is not running.
#          zmconfigd               Running
#
sed -i -e '$iexit 0' /opt/zimbra/bin/mysqladmin

/opt/zimbra/libexec/zmsetup.pl -c /tmp/config
status=$?
if [ $status -ne 0 ]; then
  echo "Failed to start MAILBOX: $status"
  exit $status
fi

su -c "/opt/zimbra/bin/zmlocalconfig -f -e mysql_bind_address=zmc-mysql mysql_port=7306 zimbra_mysql_password=zimbra" zimbra

# Change mysql config so it starts on the wrong port
sed -i -e 's/7306/7307/' /opt/zimbra/conf/my.cnf


su -c '/opt/zimbra/bin/zmcontrol restart' zimbra
su -c '/opt/zimbra/bin/zmprov ma admin zimbraMailHost zmc-mailbox' zimbra

# TODO: not sure if this is necessary
su -c /opt/zimbra/bin/zmupdateauthkeys zimbra

# start simple healthcheck so other nodes in the cluster can coordinate startup
echo "MAILBOX started"
./healthcheck.py
